#!/bin/bash

PLAYER="mpv" # use mpv, ffplay, or cvlc
STREAMS_FILE="$HOME/.config/radiostreams"
OPTION1="Connect Internet Radio Stream"
OPTION2="Stop Streaming"
OPTION3="Edit Station List"
OPTIONS="$OPTION1\n$OPTION2\n$OPTION3"
FZF_COMMAND1='fzf --layout=reverse --header=Select:'
ROFI_COMMAND1='rofi -i -dmenu -l 3 -p Select'
FZF_COMMAND2='fzf --layout=reverse --header=Select:'
ROFI_COMMAND2='rofi -i -dmenu -p Select'
FZF_COMMAND3="vim $STREAMS_FILE"
ROFI_COMMAND3="x-terminal-emulator -e vim $STREAMS_FILE"

# interface based on commandline arguments
case "$1" in
gui)
    COMMAND1=$ROFI_COMMAND1
    COMMAND2=$ROFI_COMMAND2
    COMMAND3=$ROFI_COMMAND3
    ;;
*)
    COMMAND1=$FZF_COMMAND1
    COMMAND2=$FZF_COMMAND2
    COMMAND3=$FZF_COMMAND3
    ;;
esac

start_player() {
    killall -9 $PLAYER
    sleep 0.5
    echo "Connecting to ""$CHOICE"
    echo "Opening Stream: $CHOICE"
    notify-send "Opening Stream: $CHOICE" &
    echo "$CHOICE" >/tmp/stream
    [[ "$PLAYER" == "ffplay" ]] && $PLAYER -af acompressor=threshold=-26dB:ratio=5:attack=5:release=300:makeup=9 "$URL" -probesize 256 -nodisp >/dev/null 2>&1 &
    [[ "$PLAYER" == "mpv" ]] && $PLAYER "$URL" -af "aformat=cl=stereo,acompressor=threshold=-26dB:ratio=5:attack=5:release=300:makeup=9,dynaudnorm=p=0.8:s=10" >/dev/null 2>&1 &
    [[ "$PLAYER" == "cvlc" ]] && $PLAYER "$URL" --audio-filter compressor \
        --compressor-attack 1.5 \
        --compressor-release 300 \
        --compressor-threshold -26 \
        --compressor-ratio 5 \
        --compressor-knee 3 \
        --compressor-makeup-gain 9 \
        >/dev/null 2>&1 &

    exit 0
}

stop_player() {
    echo -e "Killing any existing $PLAYER instances..."
    read -r RUNNING </tmp/stream
    echo "Closing Stream: $RUNNING"
    notify-send "Closing Stream: $RUNNING" &
    killall -9 $PLAYER
}

# select option from first menu
SELECTED="$(echo -e "$OPTIONS" | $COMMAND1)"

case $SELECTED in
$OPTION1)
    # read the list of internet audio streams
    IFS=$'\n' read -rd '' -a STREAMS <<<"$(cat "$STREAMS_FILE")"

    # select a stream from the second menu
    CHOICE="$(for i in "${STREAMS[@]}"; do echo "$i"; done | sed '/^$/d;/#.*/d' | awk -F ',' '{print $2}' | $COMMAND2)"
    [[ -z "$CHOICE" ]] && echo "No selection..." && exit 1
    # grep for the correct stream url
    URL="$(for i in "${STREAMS[@]}"; do echo "$i"; done | grep "${CHOICE}" | awk -F ',' '{print $1}' | sed 's/^ /d;/#.*/d')" && start_player
    ;;
$OPTION2)
    # cleanly stop the player
    stop_player
    ;;
$OPTION3)
    # edit the list of streaming stations
    $COMMAND3
    ;;
esac
