#!/bin/bash

# Copyright (c) 2021 by Philip Collier, github.com/AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

PLAYER="mpv" # use mpv or cvlc
STREAMS_FILE="$HOME/.config/radiostreams"
OPTION1="Connect Internet Radio Stream"
OPTION2="Stop Streaming"
OPTION3="Edit Station List"
OPTIONS="$OPTION1\n$OPTION2\n$OPTION3"
FZF_COMMAND1='fzf --layout=reverse --header=Select:'
ROFI_COMMAND1='rofi -dmenu -l 3 -p Select'
FZF_COMMAND2='fzf --layout=reverse --header=Select:'
ROFI_COMMAND2='rofi -dmenu -p Select'
FZF_COMMAND3="vim $STREAMS_FILE"
ROFI_COMMAND3="x-terminal-emulator -e vim $STREAMS_FILE"

# interface based on commandline arguments
case "$1" in
    gui)
        COMMAND1=$ROFI_COMMAND1
        COMMAND2=$ROFI_COMMAND2
        COMMAND3=$ROFI_COMMAND3
    ;;
    *)
        COMMAND1=$FZF_COMMAND1
        COMMAND2=$FZF_COMMAND2
        COMMAND3=$FZF_COMMAND3
    ;;
esac

start_player(){
killall -9 $PLAYER
sleep 0.5
echo "Connecting to "$CHOICE
echo "Opening Stream: $CHOICE"
WINDOW=$(yad --height=30 --width=400 --no-buttons --text-align=center \
    --fixed --text="Opening Stream: $CHOICE") &
echo "$CHOICE" > /tmp/stream
[[ "$PLAYER" == "mpv" ]] && $PLAYER $URL -af "aformat=cl=stereo,dynaudnorm" >/dev/null 2>&1 &
[[ "$PLAYER" == "cvlc" ]] && $PLAYER $URL --audio-filter compressor \
	--compressor-attack 1.5 \
	--compressor-release 300 \
	--compressor-threshold -26 \
	--compressor-ratio 10 \
	--compressor-knee 3 \
	--compressor-makeup-gain 12 \
        >/dev/null 2>&1 &

exit 0
}

stop_player(){
echo -e "Killing any existing $PLAYER instances..."
read -r RUNNING < /tmp/stream
echo "Closing Stream: $RUNNING"
WINDOW=$(yad --height=30 --width=400 --no-buttons --text-align=center \
    --fixed --text="Closing Stream: $RUNNING") &
killall -9 $PLAYER
}

# select option from first menu
SELECTED="$(echo -e "$OPTIONS" | $COMMAND1 )"

case $SELECTED in
  $OPTION1)
    # read the list of internet audio streams
    readarray STREAMS < $STREAMS_FILE
    # select a stream from the second menu
    CHOICE="$(echo "${STREAMS[@]}" | sed '/^$/d;/#.*/d' | awk -F \" '{print $2}' | $COMMAND2 )"
    [[ -z "$CHOICE" ]] && echo "No selection..." && exit 1
    # grep for the correct stream url
    URL="$(echo "${STREAMS[@]}" | grep "${CHOICE}" | awk '{print $1}'| sed 's/^ /d;/#.*/d')" && start_player
    ;;
  $OPTION2)
      # cleanly stop the player
      stop_player
    ;;
  $OPTION3)
      # edit the list of streaming stations
      $COMMAND3
    ;;
esac
